[build]
    publish = "www"
    command = "swift run -c release swiftysites --clean"

[build.environment]
    SWIFT_VERSION = "5.5"

[[headers]]
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"
